# Generated by Django 4.2.7 on 2024-02-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('CustomerEmail', models.EmailField(max_length=254)),
                ('CustomerPassword', models.CharField(max_length=50)),
                ('ConfirmPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bluse', 'Bluse'), ('Dress', 'Dress'), ('Jacket', 'Jacket'), ('Jumpsuit', 'Jumpsuit'), ('Kurta-Kurti', 'Kurta-Kurti'), ('Lehenga', 'Lehenga'), ('Salwar-Suit', 'Salwar-Suit'), ('Ready-To-wear-Saree', 'Ready-To-wear-Saree'), ('Shirt', 'Shirt'), ('Skirt', 'Skirt'), ('Top', 'Top'), ('Trouser', 'Trouser')], max_length=50)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductDetails', models.TextField()),
                ('img1', models.FileField(upload_to='products/')),
            ],
        ),
    ]
