# Generated by Django 4.2.7 on 2024-02-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Blouse', 'Blouse'), ('Dress', 'Dress'), ('Jacket', 'Jacket'), ('Jumpsuit', 'Jumpsuit'), ('Kurta-Kurti', 'Kurta-Kurti'), ('Lehenga', 'Lehenga'), ('Salwar-Suit', 'Salwar-Suit'), ('Ready-To-wear-Saree', 'Ready-To-wear-Saree'), ('Shirt', 'Shirt'), ('Skirt', 'Skirt'), ('Top', 'Top'), ('Trouser', 'Trouser')], max_length=50),
        ),
    ]
