# Generated by Django 4.2.7 on 2024-02-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0002_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
                ('fabric', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('neck', models.CharField(blank=True, max_length=50, null=True)),
                ('overbust', models.CharField(blank=True, max_length=50, null=True)),
                ('bust', models.CharField(blank=True, max_length=50, null=True)),
                ('waist', models.CharField(blank=True, max_length=50, null=True)),
                ('hips', models.CharField(blank=True, max_length=50, null=True)),
                ('neckToAboveKnee', models.CharField(blank=True, max_length=50, null=True)),
                ('neckToHeel', models.CharField(blank=True, max_length=50, null=True)),
                ('armLength', models.CharField(blank=True, max_length=50, null=True)),
                ('aboveKneeToAnkle', models.CharField(blank=True, max_length=50, null=True)),
                ('shoulderSeam', models.CharField(blank=True, max_length=50, null=True)),
                ('armHole', models.CharField(blank=True, max_length=50, null=True)),
                ('foreArm', models.CharField(blank=True, max_length=50, null=True)),
                ('wrist', models.CharField(blank=True, max_length=50, null=True)),
                ('vNeckCut', models.CharField(blank=True, max_length=50, null=True)),
                ('shoulderToWaist', models.CharField(blank=True, max_length=50, null=True)),
                ('waistToAboveKnee', models.CharField(blank=True, max_length=50, null=True)),
                ('productdescription', models.TextField(blank=True, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailor.products')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailor.customer')),
            ],
        ),
    ]
