# Generated by Django 4.2.7 on 2024-02-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='aboveKneeToAnkle',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='armHole',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='armLength',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='bust',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='foreArm',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='hips',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='neck',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='neckToAboveKnee',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='neckToHeel',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='overbust',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='productdescription',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='shoulderSeam',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='shoulderToWaist',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='vNeckCut',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='waist',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='waistToAboveKnee',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='wrist',
        ),
    ]
