# Generated by Django 4.2.7 on 2024-02-21 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0005_sizechart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tailor.sizechart'),
        ),
    ]
